name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx eslint .

  docker:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest